/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DesktopRouteImport } from './routes/desktop'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as OnboardingQuestionnaireRouteImport } from './routes/onboarding/questionnaire'
import { Route as OnboardingParqRouteImport } from './routes/onboarding/parq'
import { Route as OnboardingJointsRouteImport } from './routes/onboarding/joints'
import { Route as OnboardingGoalRouteImport } from './routes/onboarding/goal'
import { Route as OnboardingDisclaimerRouteImport } from './routes/onboarding/disclaimer'
import { Route as AppScreenRouteImport } from './routes/app/screen'
import { Route as AppProgressRouteImport } from './routes/app/progress'
import { Route as AppProgramRouteImport } from './routes/app/program'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AdminExercisesRouteImport } from './routes/admin.exercises'
import { Route as AppScreenIndexRouteImport } from './routes/app/screen.index'
import { Route as AppScreenRunRouteImport } from './routes/app/screen.run'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopRoute = DesktopRouteImport.update({
  id: '/desktop',
  path: '/desktop',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const OnboardingQuestionnaireRoute = OnboardingQuestionnaireRouteImport.update({
  id: '/questionnaire',
  path: '/questionnaire',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingParqRoute = OnboardingParqRouteImport.update({
  id: '/parq',
  path: '/parq',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingJointsRoute = OnboardingJointsRouteImport.update({
  id: '/joints',
  path: '/joints',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingGoalRoute = OnboardingGoalRouteImport.update({
  id: '/goal',
  path: '/goal',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingDisclaimerRoute = OnboardingDisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const AppScreenRoute = AppScreenRouteImport.update({
  id: '/screen',
  path: '/screen',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProgramRoute = AppProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminExercisesRoute = AdminExercisesRouteImport.update({
  id: '/admin/exercises',
  path: '/admin/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const AppScreenIndexRoute = AppScreenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppScreenRoute,
} as any)
const AppScreenRunRoute = AppScreenRunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => AppScreenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/desktop': typeof DesktopRoute
  '/disclaimer': typeof DisclaimerRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/exercises': typeof AdminExercisesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/program': typeof AppProgramRoute
  '/app/progress': typeof AppProgressRoute
  '/app/screen': typeof AppScreenRouteWithChildren
  '/onboarding/disclaimer': typeof OnboardingDisclaimerRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/joints': typeof OnboardingJointsRoute
  '/onboarding/parq': typeof OnboardingParqRoute
  '/onboarding/questionnaire': typeof OnboardingQuestionnaireRoute
  '/app/': typeof AppIndexRoute
  '/app/screen/run': typeof AppScreenRunRoute
  '/app/screen/': typeof AppScreenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/desktop': typeof DesktopRoute
  '/disclaimer': typeof DisclaimerRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/exercises': typeof AdminExercisesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/program': typeof AppProgramRoute
  '/app/progress': typeof AppProgressRoute
  '/onboarding/disclaimer': typeof OnboardingDisclaimerRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/joints': typeof OnboardingJointsRoute
  '/onboarding/parq': typeof OnboardingParqRoute
  '/onboarding/questionnaire': typeof OnboardingQuestionnaireRoute
  '/app': typeof AppIndexRoute
  '/app/screen/run': typeof AppScreenRunRoute
  '/app/screen': typeof AppScreenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/desktop': typeof DesktopRoute
  '/disclaimer': typeof DisclaimerRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/exercises': typeof AdminExercisesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/program': typeof AppProgramRoute
  '/app/progress': typeof AppProgressRoute
  '/app/screen': typeof AppScreenRouteWithChildren
  '/onboarding/disclaimer': typeof OnboardingDisclaimerRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/joints': typeof OnboardingJointsRoute
  '/onboarding/parq': typeof OnboardingParqRoute
  '/onboarding/questionnaire': typeof OnboardingQuestionnaireRoute
  '/app/': typeof AppIndexRoute
  '/app/screen/run': typeof AppScreenRunRoute
  '/app/screen/': typeof AppScreenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/about'
    | '/contact'
    | '/desktop'
    | '/disclaimer'
    | '/premium'
    | '/privacy'
    | '/terms'
    | '/admin/exercises'
    | '/app/profile'
    | '/app/program'
    | '/app/progress'
    | '/app/screen'
    | '/onboarding/disclaimer'
    | '/onboarding/goal'
    | '/onboarding/joints'
    | '/onboarding/parq'
    | '/onboarding/questionnaire'
    | '/app/'
    | '/app/screen/run'
    | '/app/screen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/about'
    | '/contact'
    | '/desktop'
    | '/disclaimer'
    | '/premium'
    | '/privacy'
    | '/terms'
    | '/admin/exercises'
    | '/app/profile'
    | '/app/program'
    | '/app/progress'
    | '/onboarding/disclaimer'
    | '/onboarding/goal'
    | '/onboarding/joints'
    | '/onboarding/parq'
    | '/onboarding/questionnaire'
    | '/app'
    | '/app/screen/run'
    | '/app/screen'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/onboarding'
    | '/about'
    | '/contact'
    | '/desktop'
    | '/disclaimer'
    | '/premium'
    | '/privacy'
    | '/terms'
    | '/admin/exercises'
    | '/app/profile'
    | '/app/program'
    | '/app/progress'
    | '/app/screen'
    | '/onboarding/disclaimer'
    | '/onboarding/goal'
    | '/onboarding/joints'
    | '/onboarding/parq'
    | '/onboarding/questionnaire'
    | '/app/'
    | '/app/screen/run'
    | '/app/screen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DesktopRoute: typeof DesktopRoute
  DisclaimerRoute: typeof DisclaimerRoute
  PremiumRoute: typeof PremiumRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AdminExercisesRoute: typeof AdminExercisesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop': {
      id: '/desktop'
      path: '/desktop'
      fullPath: '/desktop'
      preLoaderRoute: typeof DesktopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/onboarding/questionnaire': {
      id: '/onboarding/questionnaire'
      path: '/questionnaire'
      fullPath: '/onboarding/questionnaire'
      preLoaderRoute: typeof OnboardingQuestionnaireRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/parq': {
      id: '/onboarding/parq'
      path: '/parq'
      fullPath: '/onboarding/parq'
      preLoaderRoute: typeof OnboardingParqRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/joints': {
      id: '/onboarding/joints'
      path: '/joints'
      fullPath: '/onboarding/joints'
      preLoaderRoute: typeof OnboardingJointsRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/goal': {
      id: '/onboarding/goal'
      path: '/goal'
      fullPath: '/onboarding/goal'
      preLoaderRoute: typeof OnboardingGoalRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/disclaimer': {
      id: '/onboarding/disclaimer'
      path: '/disclaimer'
      fullPath: '/onboarding/disclaimer'
      preLoaderRoute: typeof OnboardingDisclaimerRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/app/screen': {
      id: '/app/screen'
      path: '/screen'
      fullPath: '/app/screen'
      preLoaderRoute: typeof AppScreenRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/program': {
      id: '/app/program'
      path: '/program'
      fullPath: '/app/program'
      preLoaderRoute: typeof AppProgramRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/exercises': {
      id: '/admin/exercises'
      path: '/admin/exercises'
      fullPath: '/admin/exercises'
      preLoaderRoute: typeof AdminExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/screen/': {
      id: '/app/screen/'
      path: '/'
      fullPath: '/app/screen/'
      preLoaderRoute: typeof AppScreenIndexRouteImport
      parentRoute: typeof AppScreenRoute
    }
    '/app/screen/run': {
      id: '/app/screen/run'
      path: '/run'
      fullPath: '/app/screen/run'
      preLoaderRoute: typeof AppScreenRunRouteImport
      parentRoute: typeof AppScreenRoute
    }
  }
}

interface AppScreenRouteChildren {
  AppScreenRunRoute: typeof AppScreenRunRoute
  AppScreenIndexRoute: typeof AppScreenIndexRoute
}

const AppScreenRouteChildren: AppScreenRouteChildren = {
  AppScreenRunRoute: AppScreenRunRoute,
  AppScreenIndexRoute: AppScreenIndexRoute,
}

const AppScreenRouteWithChildren = AppScreenRoute._addFileChildren(
  AppScreenRouteChildren,
)

interface AppRouteRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppProgramRoute: typeof AppProgramRoute
  AppProgressRoute: typeof AppProgressRoute
  AppScreenRoute: typeof AppScreenRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppProgramRoute: AppProgramRoute,
  AppProgressRoute: AppProgressRoute,
  AppScreenRoute: AppScreenRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingDisclaimerRoute: typeof OnboardingDisclaimerRoute
  OnboardingGoalRoute: typeof OnboardingGoalRoute
  OnboardingJointsRoute: typeof OnboardingJointsRoute
  OnboardingParqRoute: typeof OnboardingParqRoute
  OnboardingQuestionnaireRoute: typeof OnboardingQuestionnaireRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingDisclaimerRoute: OnboardingDisclaimerRoute,
  OnboardingGoalRoute: OnboardingGoalRoute,
  OnboardingJointsRoute: OnboardingJointsRoute,
  OnboardingParqRoute: OnboardingParqRoute,
  OnboardingQuestionnaireRoute: OnboardingQuestionnaireRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DesktopRoute: DesktopRoute,
  DisclaimerRoute: DisclaimerRoute,
  PremiumRoute: PremiumRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AdminExercisesRoute: AdminExercisesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
